tag_combo_5 = {
    ("AOE", "Debuff"): "Meteorite, Sesa",
    ("AoE", "DPS"): "Ayerscarpe",
    ("AoE", "Nuker"): "Leonhardt",
    ("Caster", "Nuker"): "Leonhardt",
    ("Caster", "DPS"): "Nightmare MUST BE 3RD TAG SLOW",
    ("Caster", "Healing"): "Nightmare",
    ("DPS", "Healing"): "Nightmare",
    ("AoE", "Defense"): "Beeswax",
    ("Caster", "Defense"): "Beeswax",
    ("Defense", "Ranged"): "Beeswax",
    ("Crowd-Control", "DP-Recovery"): "Texas",
    ("Crowd-Control", "Vanguard"): "Texas",
    ("Crowd-Control", "Fast-Redeploy"): "Projekt Red",
    ("Crowd-Control", "Specialist"): "Projekt Red",
    ("Crowd-Control", "Melee"): "Projekt Red, Texas",
    ("Crowd-Control", "Supporter"): "Glaucus, Mayer",
    ("Crowd-Control", "Slow"): "Glaucus",
    ("DP-Recovery", "Support"): "Elysium, Zima",
    ("Support", "Vanguard"): "Elysium, Zima",
    ("DPS", "Defender"): "Asbestos, Liskarm, Vulcan",
    ("DPS", "Defense"): "Asbestos, Astesia, Liskarm, Vulcan",
    ("DPS", "Nuker"): "Firewatch MUST BE 3RD TAG RANGED",
    ("DPS", "Shift"): "Cliffheart",
    ("DPS", "Supporter"): "Istina",
    ("Debuff", "Fast-Redeploy"): "Waai Fu",
    ("Debuff", "Melee"): "Waai Fu",
    ("Debuff", "Specialist"): "Waai Fu",
    ("Debuff", "Supporter"): "Pramanix, Shamare",
    ("Defender", "Shift"): "Croissant",
    ("Defense", "Shift"): "Croissant",
    ("Defender", "Survival"): "Vulcan",
    ("Defense", "Survival"): "Vulcan",
    ("Defense", "Guard"): "Astesia",
    ("Nuker", "Ranged"): "Firewatch, Leonhardt",
    ("Nuker", "Sniper"): "Firewatch",
    ("Shift", "Slow"): "FEater",
    ("Specialist", "Slow"): "FEater",
    ("Specialist", "Survival"): "Manticore",
    "Summon": "Mayer",
    ("Support", "Supporter"): "Tsukinogi",
    ("Support", "Survival"): "Tsukinogi",
    ("Supporter", "Survival"): "Tsukinogi"
}
