tag_combo_4 = {
    ("AoE", "Caster"): "Greyy MUST BE 3RD TAG SLOW",
    ("AoE", "Slow"): "Greyy, Shirayuki",
    ("Caster", "Debuff"): "Haze",
    ("Caster", "Slow"): "Greyy",
    "Crowd-Control": "Click",
    ("DP-Recovery", "Healing"): "Myrtle",
    ("Healing", "Vanguard"): "Myrtle",
    ("DPS", "Debuff"): "Haze, Meteor",
    ("DPS", "Fast-Redeploy"): "Jaye",
    ("DPS", "Slow"): "Ambriel, Frostleaf, May",
    ("DPS", "Melee"): "Frostleaf MUST BE 3RD TAG SLOW",
    ("DPS", "Specialist"): "Jaye",
    ("DPS", "Support"): "Dobermann",
    ("Guard", "Support"): "Dobermann",
    "Debuff": "Haze, Meteor",
    ("Debuff", "Ranged"): "Haze, Meteor",
    ("Debuff", "Sniper"): "Meteor",
    ("Defense", "Fast-Redeploy"): "Gravel",
    ("Defense", "Specialist"): "Gravel",
    "Fast-Redeploy": "Gravel, Jaye",
    ("Guard", "Slow"): "Frostleaf",
    ("Guard", "Nuker"): "Cutter",
    ("Melee", "Nuker"): "Cutter",
    ("Healing", "Slow"): "Podenco",
    ("Healing", "Supporter"): "Podenco",
    ("Healing", "Support"): "Purestream",
    ("Medic", "Support"): "Purestream",
    ("Melee", "Slow"): "Frostleaf",
    ("Melee", "Support"): "Dobermann",
    "Nuker": "Cutter",
    ("Ranged", "Survival"): "Jessica",
    "Shift": "Rope, Shaw",
    ("Slow", "Sniper"): "Ambriel, May, Shirayuki",
    ("Sniper", "Survival"): "Jessica",
    "Specialist": "Gravel, Rope, Shaw",
    "Support": "Dobermann, Purestream"
}
